# * mysite
# * berong91
# * https://github.com/berong91/django-practice

sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.8
install:
  - pip install -q -U pip wheel setuptools
  - pip install -q Django==$DJANGO
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - pyflakes -x W src
script:
  - python manage.py check
  - python manage.py test