# * mysite
# * berong91
# * https://github.com/berong91/django-practice

language: python

python:
  - "2.6"
  - "2.7"

addons:
  postgresql: "9.3"

install:
  - pip install -q Django==1.8
  - python setup.py -q install

script: nosetests
  - python manage.py test
