# * mysite
# * berong91
# * https://github.com/berong91/django-practice

language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.10

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

script: nosetests

