# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('filename', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('rating', models.CharField(choices=[('clean', 'Alert'), ('low-risk', 'Low Risk'), ('medium-risk', 'Medium Risk'), ('high-risk', 'High Risk'), ('malicious', 'Malicious')], default='malicious', max_length=16)),
                ('submit_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('date_modified', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_reader.Source'),
        ),
    ]
