# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meta_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 17, 56, 16, 551000, tzinfo=utc), verbose_name='date modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='rating',
            field=models.CharField(choices=[('clean', 'Alert'), ('low-risk', 'Low Risk'), ('medium-risk', 'Medium Risk'), ('high-risk', 'High Risk'), ('malicious', 'Malicious')], default='malicious', max_length=16),
        ),
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
