# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_reader', '0002_auto_20160820_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='submitType',
            new_name='submit_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(primary_key=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='record',
            name='filename',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
