# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_reader', '0003_auto_20160820_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='modified_date',
            new_name='date_modified',
        ),
    ]
